### ISSUE TITLE
 Data Cart timeout

### ISSUE THREAD

**Issue by RuthPetrie** [ESGF/CDNOT#1]
With too many items it times out. 
Add a clear button to the nav bar. 
LLNL - will put notes on the wiki how to update

**Comment by RuthPetrie** [comment]
Add a clear button to nav bar

**Comment by sashakames** [comment]
The README here lists howto apply the fix:  https://github.com/earthsystemcog/cog

**Comment by sashakames** [comment]
Haven't had any problems, perhaps everyone applied the changes.
