### ISSUE TITLE
Master older than replica

### ISSUE THREAD

**Issue by martinjuckes** [ESGF/CDNOT#14]
Hi, I'm not sure if this is the right place to report this issue, but here goes:

The data set at  https://handle-esgf.dkrz.de/lp/21.14100/0c3cbc45-8d13-4f8b-ac9b-454dd6ca0a44 has an master copy at `v20190815` and newer replicas at `v20190920`.

**Comment by sashakames** [comment]
Appears that NCC published a new version dated 20210118.
