### ISSUE TITLE
updates to data node contacts file in this repo

### ISSUE THREAD

**Issue by alaniwi** [ESGF/CDNOT#18]
As the data nodes contacts list is now public at `docs/data-node-contacts.md` (having been moved from a private site), we should:

- add something to advise end-users regarding the use of this list:
   - what sort of errors might indicate that it is/isn't a data node issue
   - if it appears data-node related, then how to find out which data node they are using as opposed to index node or openid provider
   - otherwise, the appropriate alternative channel to ask for help

- consider spam-proofing the email addresses somehow  (maybe separate table columns for domain and local part of the address)

**Comment by alaniwi** [comment]
(Couldn't think of a more descriptive title for the ticket. Feel free to edit.)

**Comment by soay** [comment]
Thanks for pointing this out, Alan. I moved the page to the CDNOT secure repo.
