### ISSUE TITLE
 T1 Sites: All CMIP5 data should be published with Globus access

### ISSUE THREAD

**Issue by RuthPetrie** [ESGF/CDNOT#3]
Globus endpoints should be available for all CMIP5 data from T1 sites

**Comment by lukaszlacinski** [comment]
I wrote a script that checks if all CMIP5 files on Tier 1 sites are published with Globus access. As I checked, all CMIP5 files on Tier 1 sites data nodes (`data node` `number of CMIP5 files`):
```
aims3.llnl.gov 124446
esgf-data1.ceda.ac.uk 203387
esgf-data2.ceda.ac.uk 0
esgf.nci.org.au 219508
esgf1.dkrz.de 192424
vesg.ipsl.upmc.fr 129416
```
are published with Globus URI. On the other hand, none of CMIP5 files on other data nodes is published with Globus url:
```
crd-esgf-drc.ec.gc.ca 8808
dataserver.nccs.nasa.gov 4680
esg-dn1.nsc.liu.se 1840
esg.lasg.ac.cn 676
esg1.umr-cnrm.fr 754
esgdata.gfdl.noaa.gov 5530
esgf-data1.diasjp.net 7794
esgf-node.cmcc.it 638
esgf.ichec.ie 786
noresg.nird.sigma2.no 402
```
None of them even has GridFTP server (Globus Connect Server IO to be precise) working properly. If they had GridFTP server up and accessible, CoG on the index nodes could be configured to show Globus access based on gsiftp urls.

**Comment by RuthPetrie** [comment]
FROM LL L: 

aims3.llnl.gov 124446
esgf-data1.ceda.ac.uk 203387
esgf-data2.ceda.ac.uk 0
esgf.nci.org.au 219508
esgf1.dkrz.de 192424
vesg.ipsl.upmc.fr 129416

**Comment by RuthPetrie** [comment]
Hi Lukasz,

That is fantastic – thanks – I have marked that action as done now.

Many thanks for your help,
Ruth

**Comment by lukaszlacinski** [comment]
I also checked replicas published on the Tier 1 nodes. 11387 replica files on aims3.llnl.gov have been published without Globus access. I sent the list of the files to the LLNL admins.
