### ISSUE TITLE
Metadata errors not caught, (global attributes), Dir structure and GA not consistent

### ISSUE THREAD

**Issue by RuthPetrie** [ESGF/CDNOT#4]
PrePARE missing checks needs fixing
PCMDI to correct PrePARE
May need alt solution for directory structure vs GA

**Comment by RuthPetrie** [comment]
PrePARE will not fix directory structure. 
esgprep will check consistency between GA and filename/dir-structure 
incorporate into Python 3 version of publisher

**Comment by RuthPetrie** [comment]
No new issue of PrePARE until Feb or March.

**Comment by sashakames** [comment]
I looked into this, and given the way the publisher is designed, it would be a non-trivial change to the publisher.  But I see now above that "esgprep will check consistency between GA and filename/dir-structure". That would be great to prevent mapfile generation if the GA are inconsistent.  @glevava would this be hard to implement (in esgmapfile)?   Alternatively we would have to make a feature request to PCMDI/CMOR and then it could be done.

The future version of the publisher (for the next gen data node architecture under development now at LLNL) could have this check for sure as we would start from scratch.

**Comment by glevava** [comment]
@RuthPetrie @sashakames 
actually esgprep already do the job if it is used as recommended.
"esgdrs" checks consistency between GA and filename syntax again the esg.project.ini. Then, "esgdrs" deduces the directory structure from the GA and filename.
"esgmapfile" doesn't care about the GA and the filename but check the directory structure against the esg.project.ini. 
So, if you use "esgdrs" then "esgmapfile" it ensures full consistency between GA/dir. str./filename.

Adding the GA check in "esgmapfile" would require to open each file (which is not the case in the current release). From my point of view this overlaps what "esgdrs" does.

I prefer recommend to not use CMOR to generate the directory structure and keep PrePARE agnostic of the directory structure too. The workflow would be:
CMOR (standardisation) -> esgdrs (check GA and filename then put file in appropriate dir. str.) -> PrePARE (check variable attributes against tables and some mandatory GA unchecked by esgdrs) -> esgmapfile (generate mapfile) -> esgpublish.

What do you think?

**Comment by sashakames** [comment]
I think its good advice to revise the workflow for all to run esgdrs to get the consistency check.

**Comment by glevava** [comment]
Fully agree with @sashakames 
We can raise it during the issue review of next CDNOT telco : )
